version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_local
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data_container:/data/db

  nodeapp:
    build: .
    container_name: nodejs_app
    ports:
      - "3333:3333"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://root:example@mongodb:27017

  test:
    build: .
    container_name: nodejs_test
    depends_on:
      - mongodb
    environment:
      NODE_ENV: test
      MONGO_URL: mongodb://root:example@mongodb:27017
    command: npm run test
    volumes:
      - .:/app
    working_dir: /app

volumes:
  mongodb_data_container:
